spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "by.afinny.moneytransfer.dto.kafka"
    topics:
      producer-transfer-order-event-sender:
        path: "money_transfer_to_master_update_transfer_order"
        enabled: true
      consumer-transfer-order-event-listener:
        path: "master_to_money_transfer_update_transfer_order"
        enabled: true
      create-new-payment-producer:
        path: "money_transfer_to_master_create_payment"
        enabled: true
      create-new-payment-listener:
        path: "master_to_money_transfer_create_payment"
        enabled: true

  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true
  flyway:
    enabled: false
  cloud:
    discovery:
      enabled: false